# Generated by Django 6.0.6 on 2026-09-05 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Stable identifier for this prompt template', max_length=255)),
                ('version', models.PositiveIntegerField()),
                ('prompt_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key', '-version'],
                'indexes': [models.Index(fields=['key', '-version'], name='governance__key_428f14_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'version'), name='unique_prompt_key_version')],
            },
        ),
    ]
