# Generated by Django 6.0.6 on 2026-09-12 10:56

import django.db.models.deletion
import governance.models
from django.db import migrations, models


def seed_standard_stages(apps, schema_editor):
    EnvironmentStage = apps.get_model('governance', 'EnvironmentStage')
    for slug, name, order in governance.models.EnvironmentStage.STANDARD_STAGES:
        EnvironmentStage.objects.get_or_create(slug=slug, defaults={'name': name, 'order': order})


def unseed_standard_stages(apps, schema_editor):
    EnvironmentStage = apps.get_model('governance', 'EnvironmentStage')
    slugs = [slug for slug, _, _ in governance.models.EnvironmentStage.STANDARD_STAGES]
    EnvironmentStage.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RunPython(seed_standard_stages, unseed_standard_stages),
        migrations.AddField(
            model_name='promptversion',
            name='stage',
            field=models.ForeignKey(default=governance.models.EnvironmentStage.default_stage, help_text='Current pipeline stage for this version.', on_delete=django.db.models.deletion.PROTECT, related_name='prompt_versions', to='governance.environmentstage'),
        ),
    ]
